### ISSUE TITLE
Can't connect to bitly... proxy ?

### ISSUE THREAD

**Issue by rudzboy** [mremi/UrlShortenerBundle#3]
I am receiving this error 

An exception has been thrown during the rendering of a template ("[curl] 7: Failed connect to api-ssl.bitly.com:443; Operation now in progress [url] https://api-ssl.bitly.com/oauth/access_token")

I looked at your code, and there's no way to pass proxy info to guzzle client...

Do you have a workaround available ?

Merci ;) Thx

**Comment by mremi** [comment]
Hi,

You're (almost) right, the bundle configuration prevents you to do it: the only things you can tweak are `connect_timeout` and `timeout`. I don't know why I restricted to these options, it would be better to configure all what Guzzle supports but without checking it in this bundle. Thus, we would be able to do:

```yaml
mremi_url_shortener:
    providers:
        bitly:
            enabled:     true
            username:    your_bitly_username
            password:    your_bitly_password
            options:
                proxy:   http://username:password@192.168.16.1:10
```

Do you want to try to do it?
